root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
exclude_dir = [
    "assets",
    "tmp",
    "vendor",
    "testdata",
    "bin",
    "node_modules",
    "web",
]
args_bin = []
bin = "tmp\\main.exe"
cmd = "templ generate && cd web && npm run build && cd .. && bin\\template_formatter.exe && go build -o ./tmp/main.exe main.go"
delay = 1000
exclude_file = []
exclude_regex = ["_test.go", "_templ.go", "dist", "node_modules"]
exclude_unchanged = false
follow_symlink = false
full_bin = ""
include_dir = []
include_ext = ["go", "tpl", "tmpl", "html", "templ", "ts"]
include_file = []
kill_delay = "0s"
log = "build-errors.log"
poll = false
poll_interval = 0
post_cmd = []
pre_cmd = []
rerun = false
rerun_delay = 500
send_interrupt = false
stop_on_error = false

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
main_only = false
time = false

[misc]
clean_on_exit = false

[screen]
clear_on_rebuild = false
keep_scroll = true
